USE p4g1

GO
	CREATE SCHEMA INFANTARIO
GO

CREATE TABLE INFANTARIO.PESSOA(
ID					INT IDENTITY(1,1)	PRIMARY KEY,
NOME				VARCHAR(50)			NOT NULL,
DATA_NASCIMENTO		DATE				NOT NULL,
CC					INT					NOT NULL,
NIF					INT					NOT NULL,
MORADA				VARCHAR(100)		NOT NULL,
SEXO				VARCHAR(1)			NOT NULL		CHECK(Sexo='F' OR Sexo='M'),
);

CREATE TABLE INFANTARIO.ENCARREGADO_EDUCACAO(
ID_Pessoa			INT IDENTITY(1,1)	NOT NULL	FOREIGN KEY REFERENCES INFANTARIO.PESSOA(ID)
);

CREATE TABLE INFANTARIO.HORARIO(
DESIGNACAO			VARCHAR(60)		PRIMARY KEY,
HORA_ENTRADA		SMALLDATETIME	NOT NULL,
HORA_SAIDA			SMALLDATETIME	NOT NULL,
FUNCAO_FUNCIONARIO	VARCHAR(60)		NOT NULL		FOREIGN KEY (FUNCAO_FUNCIONARIO) REFERENCES INFANTARIO.FUNCIONARIO(FUNCAO)
);

CREATE TABLE INFANTARIO.EVENTO(
CODIGO				INT				PRIMARY KEY,
NOME				VARCHAR(60)		NOT NULL,
DESIGNACAO			VARCHAR(100)	NOT NULL
);


CREATE TABLE INFANTARIO.E_ATRIBUIDA(
IDADE_CRIANCA		INT				NOT NULL	FOREIGN KEY REFERENCES INFANTARIO.CRIANCA(IDADE),
CODIGO_SALA			INT				NOT NULL	FOREIGN KEY REFERENCES INFANTARIO.SALA(CODIGO),
ANO					INT				NOT NULL
);

CREATE TABLE INFANTARIO.PLANO_INDIVIDUAL(
CODIGO				INT				PRIMARY KEY,
DESCRIÇÃO			VARCHAR(60)		NOT NULL,
IDADE_CRIANCA		INT				NOT NULL	FOREIGN KEY REFERENCES INFANTARIO.CRIANCA(IDADE),
FUNCAO_FUNCIONARIO	VARCHAR(60)		NOT NULL	FOREIGN KEY REFERENCES INFANTARIO.FUNCIONARIO(FUNCAO),
);

CREATE TABLE INFANTARIO.DOCENTE(
FUNCAO_FUNCIONARIO	VARCHAR(60)		NOT NULL	FOREIGN KEY REFERENCES INFANTARIO.FUNCIONARIO(FUNCAO)
);


CREATE TABLE INFANTARIO.SALA(
CODIGO				INT				PRIMARY KEY,
DESCRIÇÃO			VARCHAR(60)		NOT NULL,
ID_TIPO				INT				NOT NULL	FOREIGN KEY REFERENCES INFANTARIO.TIPO(ID)
);

CREATE TABLE INFANTARIO.TIPO(
ID					INT				PRIMARY KEY,
DESCRIÇÃO			VARCHAR(60)		NOT NULL
);

CREATE TABLE INFANTARIO.RESPONSAVEL(
ANO					INT				PRIMARY KEY,
CODIGO_SALA			INT				NOT NULL	FOREIGN KEY REFERENCES INFANTARIO.SALA(CODIGO),
FUNCAO_FUNCIONARIO	VARCHAR(60)		NOT NULL	FOREIGN KEY REFERENCES INFANTARIO.FUNCIONARIO(FUNCAO)
);